// Generated by ReScript, PLEASE EDIT WITH CARE


let v = {
  x: "1",
  p: true,
  own: "z"
};

let s = {
  color: "red",
  _hover: {
    color: "blue"
  },
  extra: 1
};

export {
  v,
  s,
}
/* No side effect */
