type t = InstanceTypes.widget
@new @module("demo") external make: (~id: string) => t = "Widget"
@send external refresh: (t) => unit = "refresh"
@send external reset: (t) => unit = "reset"
@get external value: t => float = "value"
@get external id: t => string = "id"
@set external valueSet: (t, float) => unit = "value"
@set external tokenSet: (t, string) => unit = "token"
@module("demo") @scope("Widget") external create: (~id: string) => t = "create"
@module("demo") @scope("Widget") external resetStatic: unit => unit = "reset"
@module("demo") @scope("Widget") external version: string = "VERSION"
