type stringEnumsSize =
  | @as("sm") Sm
  | @as("md") Md
  | @as("lg") Lg
type stringEnumsVariant =
  | @as("primary") Primary
  | @as("secondary") Secondary
type htmlInputTypeAttribute =
  | @as("text") Text
  | @as("password") Password
  | @as("email") Email
